---
title: Kunst am Kirchberg
timezone: UTC
collections:
  artists:
    title: Artists
    output: true
    permalink: "/kuenstler/:title.html"
  artworks:
    title: Artworks
    output: true
    permalink: "/kunstwerke/:title.html"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  exhibitions:
    title: exhibitions
    output: true
    permalink: "/austellungen/:title.html"
defaults:
- scope:
    path: ''
    type: artists
  values:
    layout: artist
    image: 
    wiki: 
- scope:
    path: ''
    type: artworks
  values:
    layout: artwork
    gallery:
    - image: 
      alt: 
    price: 
    year: 
    title: 
    is_available: 
    category: 
    dimensions: 
    artist: 
    style: 
    exhibition: 
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: ''
url: ''
